name: numbers
version: git
summary: Numbers
description: YaruNavigationPage example
confinement: strict
base: core22
grade: stable
license: GPL-3.0+
icon: snap/local/numbers.png
architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: arm64
    build-for: arm64

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-branch: stable
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
    build-packages:
      - clang
      - cmake
      - curl
      - ninja-build
      - unzip
      - xz-utils
      - zip
    prime:
      - -*

  numbers:
    after: [ flutter-git ]
    plugin: nil
    source: .
    override-build: |
      set -eux
      flutter doctor
      flutter pub get
      flutter build linux --release -v
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/

apps:
  numbers:
    command: bin/numbers
    desktop: bin/data/flutter_assets/assets/numbers.desktop
    extensions: [gnome]
    plugs:
      - network
